version: "3.8"

services:
  panasonic-mqtt-remote:
    build:
      context: .
      dockerfile: Dockerfile
    image: panasonic-viera:latest
    container_name: panasonic-mqtt-remote
    restart: unless-stopped
    depends_on:
      - mqtt
    env_file:
      - .env